blank_issues_enabled: false
contact_links:
  - name: OpenHostingNOC Documentation
    url: https://github.com/samsesh/OpenHostingNOC/wiki
    about: Check the wiki before opening an issue
  - name: Donate
    url: https://donate.samsesh.net
    about: Support the project
