#!/usr/bin/env bash
# =============================================================================
# OpenHostingNOC - Environment Generator
# =============================================================================
# Generates .env for quick or full deployment.
#   ./scripts/generate-env.sh           # interactive
#   ./scripts/generate-env.sh --quick    # non-interactive quick setup
#   ./scripts/generate-env.sh --full     # non-interactive full setup prompts
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
log_info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step()  { echo -e "\n${CYAN}════════════════════════════════════════════${NC}"; echo -e "${CYAN}  $1${NC}"; echo -e "${CYAN}════════════════════════════════════════════${NC}"; }

detect_ip() {
    local ip=""
    ip=$(ip route get 1 2>/dev/null | awk '{print $NF; exit}') || true
    if [[ -z "$ip" ]]; then
        ip=$(hostname -I 2>/dev/null | awk '{print $1}') || true
    fi
    if [[ -z "$ip" ]]; then
        ip="127.0.0.1"
    fi
    echo "$ip"
}

random_pass() {
    openssl rand -hex 16 2>/dev/null || date +%s | md5sum | head -c 16
}

generate_quick() {
    local ip="$1"
    local domain="${ip}-${ip}.nip.io"
    # Replace dots with hyphens for nip.io format
    domain="${ip//./-}.nip.io"

    log_step "Quick Setup - using nip.io domain: $domain"

    cat > "${PROJECT_DIR}/.env" << ENVEOF
# =============================================================================
# OpenHostingNOC - Quick Setup (Generated by generate-env.sh --quick)
# =============================================================================
DOMAIN=${domain}
TIMEZONE=UTC

# Traefik - HTTP only (no TLS)
TRAEFIK_PORT=80
TRAEFIK_ACME_EMAIL=
TRAEFIK_ENTRYPOINT_HTTP=80
TRAEFIK_ENTRYPOINT_HTTPS=8443
TRAEFIK_CPU=0.5
TRAEFIK_MEM=256M

# Auth Service
AUTH_SECRET_KEY=quickstart-$(random_pass)
AUTH_SESSION_MAX_AGE=86400
AUTH_CPU=0.25
AUTH_MEM=128M

# LDAP
USE_LDAP=true
LDAP_HOST=openldap
LDAP_PORT=389
LDAP_BASE_DN=dc=noc,dc=example,dc=com
LDAP_BIND_DN=cn=admin,dc=noc,dc=example,dc=com
LDAP_BIND_PASSWORD=admin
LDAP_SEARCH_FILTER=(uid=%s)
LDAP_USER_FILTER=(objectClass=posixAccount)
LDAP_ADMIN_GROUP=cn=noc-admin,ou=groups,dc=noc,dc=example,dc=com
LDAP_TLS=false
OPENLDAP_ORGANISATION=OpenHostingNOC
OPENLDAP_DOMAIN=noc.example.com
OPENLDAP_ADMIN_PASSWORD=admin

# MariaDB
MARIADB_ROOT_PASSWORD=admin
MARIADB_DATABASE=librenms
MARIADB_USER=librenms
MARIADB_PASSWORD=admin
MARIADB_CPU=1
MARIADB_MEM=512M
MARIADB_INNODB_BUFFER_POOL_SIZE=128M
MARIADB_INNODB_LOG_FILE_SIZE=32M
MARIADB_MAX_CONNECTIONS=100
MARIADB_TMP_TABLE_SIZE=16M

# Redis
REDIS_PASSWORD=admin

# LibreNMS
LIBRENMS_DB_PASSWORD=admin
LIBRENMS_LDAP_ENABLED=true
LIBRENMS_LDAP_SERVER=openldap
LIBRENMS_LDAP_PORT=389
LIBRENMS_LDAP_BASE=dc=noc,dc=example,dc=com
LIBRENMS_LDAP_BIND_DN=cn=admin,dc=noc,dc=example,dc=com
LIBRENMS_LDAP_BIND_PASSWORD=admin
LIBRENMS_CPU=1
LIBRENMS_MEM=1G

# Grafana
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=admin
GRAFANA_LDAP_ENABLED=true
GRAFANA_LDAP_HOST=openldap
GRAFANA_LDAP_PORT=389
GRAFANA_LDAP_BASE_DN=dc=noc,dc=example,dc=com
GRAFANA_LDAP_BIND_DN=cn=admin,dc=noc,dc=example,dc=com
GRAFANA_LDAP_BIND_PASSWORD=admin
GRAFANA_CPU=0.5
GRAFANA_MEM=256M

# Prometheus
PROMETHEUS_CPU=1
PROMETHEUS_MEM=2G
PROMETHEUS_RETENTION_TIME=30d
PROMETHEUS_RETENTION_SIZE=10GB

# Alertmanager
ALERTMANAGER_CPU=0.25
ALERTMANAGER_MEM=256M

# Loki
LOKI_CPU=0.5
LOKI_MEM=512M
LOKI_RETENTION_HOURS=168

# ntopng
NTOPNG_CPU=1
NTOPNG_MEM=1G

# OpenSearch
OPENSEARCH_CPU=1
OPENSEARCH_MEM=2G
OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin
OPENSEARCH_JVM_HEAP_SIZE=1g

# OpenSearch Dashboards
OPENSEARCH_DASHBOARDS_CPU=0.5
OPENSEARCH_DASHBOARDS_MEM=256M

# Logging
LOG_LEVEL=info
LOG_DRIVER=json-file
LOG_MAX_SIZE=10m
LOG_MAX_FILE=3

# Docker Compose Profile
COMPOSE_PROFILE=full
ENVEOF

    echo ""
    log_info "Default credentials (CHANGE for production):"
    echo -e "  ${YELLOW}Grafana / LDAP Admin / MariaDB:${NC} admin / admin"
    echo -e "  ${YELLOW}Traefik Dashboard:${NC} admin / admin"
    echo ""
    log_info ".env generated for quick setup using nip.io domain: ${domain}"
    log_info "Access services at http://<THIS_IP>:<PORT> (no TLS)"
}

generate_full() {
    log_step "Full Setup"

    local domain=""
    local email=""
    local pass_admin=""
    local pass_ldap=""
    local pass_db=""
    local pass_redis=""
    local pass_grafana=""
    local pass_os=""
    local pass_os_admin=""
    local pass_ntopng=""

    read -r -p "Domain (e.g. noc.example.com): " domain
    while [[ -z "$domain" ]]; do
        read -r -p "Domain cannot be empty: " domain
    done

    read -r -p "Let's Encrypt email (for cert expiry notices): " email

    # Generate random passwords
    pass_admin=$(random_pass)
    pass_ldap=$(random_pass)
    pass_db=$(random_pass)
    pass_redis=$(random_pass)
    pass_grafana=$(random_pass)
    pass_os=$(random_pass)
    pass_os_admin=$(random_pass)
    pass_ntopng=$(random_pass)

    echo ""
    log_info "Generated secure passwords (saved to .env)"

    echo ""
    echo -e "${YELLOW}Optional: Configure alerting tokens${NC}"
    echo -e "  (press Enter to skip, you can add them later in .env)"
    read -r -p "Telegram Bot Token: " tg_token
    read -r -p "Telegram Chat ID (Critical): " tg_chat
    read -r -p "Discord Webhook URL: " discord_url
    read -r -p "Slack Webhook URL: " slack_url

    cat > "${PROJECT_DIR}/.env" << ENVEOF
# =============================================================================
# OpenHostingNOC - Full Setup (Generated by generate-env.sh --full)
# =============================================================================
DOMAIN=${domain}
TIMEZONE=UTC

# Traefik
TRAEFIK_PORT=80
TRAEFIK_ENTRYPOINT_HTTP=80
TRAEFIK_ENTRYPOINT_HTTPS=443
TRAEFIK_ACME_EMAIL=${email}
TRAEFIK_CPU=1
TRAEFIK_MEM=512M

# Auth Service
AUTH_SECRET_KEY=$(random_pass)
AUTH_SESSION_MAX_AGE=86400
AUTH_CPU=0.25
AUTH_MEM=128M

# LDAP
USE_LDAP=true
LDAP_HOST=openldap
LDAP_PORT=389
LDAP_BASE_DN=dc=noc,dc=${domain#*.},dc=com
LDAP_BIND_DN=cn=admin,dc=noc,dc=${domain#*.},dc=com
LDAP_BIND_PASSWORD=${pass_ldap}
LDAP_SEARCH_FILTER=(uid=%s)
LDAP_USER_FILTER=(objectClass=posixAccount)
LDAP_ADMIN_GROUP=cn=noc-admin,ou=groups,dc=noc,dc=${domain#*.},dc=com
LDAP_TLS=false
OPENLDAP_ORGANISATION=OpenHostingNOC
OPENLDAP_DOMAIN=${domain}
OPENLDAP_ADMIN_PASSWORD=${pass_ldap}

# MariaDB
MARIADB_ROOT_PASSWORD=${pass_db}
MARIADB_DATABASE=librenms
MARIADB_USER=librenms
MARIADB_PASSWORD=${pass_db}
MARIADB_CPU=1
MARIADB_MEM=512M
MARIADB_INNODB_BUFFER_POOL_SIZE=256M
MARIADB_INNODB_LOG_FILE_SIZE=64M
MARIADB_MAX_CONNECTIONS=150
MARIADB_TMP_TABLE_SIZE=32M

# Redis
REDIS_PASSWORD=${pass_redis}

# LibreNMS
LIBRENMS_DB_PASSWORD=${pass_db}
LIBRENMS_LDAP_ENABLED=true
LIBRENMS_LDAP_SERVER=openldap
LIBRENMS_LDAP_PORT=389
LIBRENMS_LDAP_BASE=dc=noc,dc=${domain#*.},dc=com
LIBRENMS_LDAP_BIND_DN=cn=admin,dc=noc,dc=${domain#*.},dc=com
LIBRENMS_LDAP_BIND_PASSWORD=${pass_ldap}
LIBRENMS_CPU=1
LIBRENMS_MEM=1G

# Grafana
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=${pass_grafana}
GRAFANA_LDAP_ENABLED=true
GRAFANA_LDAP_HOST=openldap
GRAFANA_LDAP_PORT=389
GRAFANA_LDAP_BASE_DN=dc=noc,dc=${domain#*.},dc=com
GRAFANA_LDAP_BIND_DN=cn=admin,dc=noc,dc=${domain#*.},dc=com
GRAFANA_LDAP_BIND_PASSWORD=${pass_ldap}
GRAFANA_CPU=0.5
GRAFANA_MEM=256M

# Prometheus
PROMETHEUS_CPU=1
PROMETHEUS_MEM=4G
PROMETHEUS_RETENTION_TIME=90d
PROMETHEUS_RETENTION_SIZE=50GB

# Alertmanager
ALERTMANAGER_CPU=0.25
ALERTMANAGER_MEM=256M

# Loki
LOKI_CPU=0.5
LOKI_MEM=1G
LOKI_RETENTION_HOURS=744

# ntopng
NTOPNG_CPU=1
NTOPNG_MEM=4G

# OpenSearch
OPENSEARCH_CPU=2
OPENSEARCH_MEM=4G
OPENSEARCH_INITIAL_ADMIN_PASSWORD=${pass_os_admin}
OPENSEARCH_JVM_HEAP_SIZE=2g

# OpenSearch Dashboards
OPENSEARCH_DASHBOARDS_CPU=0.5
OPENSEARCH_DASHBOARDS_MEM=256M

# Logging
LOG_LEVEL=info
LOG_DRIVER=json-file
LOG_MAX_SIZE=10m
LOG_MAX_FILE=3

# Alerting
TELEGRAM_BOT_TOKEN=${tg_token}
TELEGRAM_CHAT_ID_CRITICAL=${tg_chat}
DISCORD_WEBHOOK_URL=${discord_url}
SLACK_WEBHOOK_URL=${slack_url}

# Docker Compose Profile
COMPOSE_PROFILE=full
ENVEOF

    echo ""
    log_info ".env generated for ${domain}"
    echo ""
    echo -e "${YELLOW}Important:${NC} Save these passwords securely!"
    echo -e "  ${YELLOW}LDAP / MariaDB / Redis:${NC} ${pass_ldap} / ${pass_db} / ${pass_redis}"
    echo -e "  ${YELLOW}Grafana:${NC} admin / ${pass_grafana}"
    echo -e "  ${YELLOW}OpenSearch:${NC} admin / ${pass_os_admin}"
    echo -e "  ${YELLOW}Traefik Dashboard:${NC} admin / admin"
    echo ""
    log_info "Run ./scripts/install.sh to deploy"
}

# ---- Main ----
log_step "OpenHostingNOC - Environment Generator"

if [[ -f "${PROJECT_DIR}/.env" ]]; then
    echo ""
    log_warn ".env already exists at ${PROJECT_DIR}/.env"
    read -r -p "Overwrite? (y/N): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        log_info "Keeping existing .env"
        exit 0
    fi
    echo ""
fi

if [[ "${1:-}" == "--quick" ]]; then
    local_ip=$(detect_ip)
    generate_quick "$local_ip"
elif [[ "${1:-}" == "--full" ]]; then
    generate_full
else
    echo ""
    echo -e "  ${CYAN}1)${NC} Quick Setup  — nip.io domain, no TLS, default passwords"
    echo -e "  ${CYAN}2)${NC} Full Setup   — real domain, Let's Encrypt TLS, secure passwords"
    echo ""
    read -r -p "Choose (1/2): " mode
    case "$mode" in
        1) local_ip=$(detect_ip); generate_quick "$local_ip" ;;
        2) generate_full ;;
        *) log_error "Invalid choice"; exit 1 ;;
    esac
fi
