name: Sync Wiki
on:
  push:
    branches: [main, Localhost]
    paths:
      - '.github/wiki/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: spenserblack/actions-wiki@v0.3.0
        with:
          path: .github/wiki
          token: ${{ secrets.GITHUB_TOKEN }}
